export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";
export const ACCOUNTS_FAILED = "ACCOUNTS_FAILED";
export const ADD_ACCOUNTS = "ADD_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DEL_ACCOUNT = "DEL_ACCOUNT";
export const JWTTOKEN_OK = "JWTTOKEN_OK";
export const JWTTOKEN_FAILED = "JWTTOKEN_FAILED";
export const JWTTOKEN_LOADING = "JWTTOKEN_LOADING";
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const SETTINGS_FAILED = "SETTINGS_FAILED";
export const ADD_SETTINGS = "ADD_SETTINGS";
export const ADD_SETTING = "ADD_SETTING";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
