export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";
export const ACCOUNTS_FAILED = "ACCOUNTS_FAILED";
export const ADD_ACCOUNTS = "ADD_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const JWTTOKEN_OK = "JWTTOKEN_OK";
export const JWTTOKEN_FAILED = "JWTTOKEN_FAILED";
export const JWTTOKEN_LOADING = "JWTTOKEN_LOADING";
